### ISSUE TITLE
Remove my token information #14769

### ISSUE THREAD

**Issue by Pengucci** [solana-labs/token-list#14945] opened 2022-01-20 19:02 UTC
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

if you please remove all the coin  information name 'shradded apes' or merge the pull request because i need to change the name of the token , if merge is not possible kindly remove the token information of the 'shredded apes' , i will the new pull request then.
Thanks

**Comment by keone** [comment] 2022-01-20 19:10
duplicate of #14912

**Closed** 2022-01-20 19:11 UTC
