### ISSUE TITLE
Phantom wallet does not recognise token

### ISSUE THREAD

**Issue by punikus** [solana-labs/token-list#12240] opened 2022-01-03 23:14 UTC
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Can you help please, my pr- change carbonado #12115

**Comment by keone** [comment] 2022-01-05 05:22
duplicate of #12189

**Closed by keone** 2022-01-05 05:22 UTC
