### ISSUE TITLE
BMRC COIN info missing on wallet

### ISSUE THREAD

**Issue by NCBEASTMODERC** [solana-labs/token-list#12473] opened 2022-01-05 04:15 UTC
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

After a successful merge, token information like name and logo still do not appear in Phanom wallet or on Solflare

#12296

Thank you

**Comment by keone** [comment] 2022-01-05 05:22
duplicate of #12189

**Closed by keone** 2022-01-05 05:22 UTC
