### ISSUE TITLE
Build&Publish action keeps being failed

### ISSUE THREAD

**Issue by tuphan-dn** [solana-labs/token-list#8462] opened 2021-12-16 07:01 UTC
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- The log from Git Actions: `error Couldn't publish package: "https://registry.npmjs.org/@solana%2fspl-token-registry: Payload Too Large"`

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment] 2021-12-16 16:44
duplicate of https://github.com/solana-labs/token-list/issues/8358

**Closed by keone** 2021-12-16 16:44 UTC
