### ISSUE TITLE
Update Logo due to it not showing on SolScan

### ISSUE THREAD

**Issue by Jacob130000x** [solana-labs/token-list#13496] opened 2022-01-11 11:57 UTC
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
The logo uploaded isn't coming up on SolScan, I have reuploaded a new logo with a more uniform size 800 x 800px and removed white background.
Please update my token logo with the follwoing: 

PR: https://github.com/solana-labs/token-list/pull/13493
#13493

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
![Logo issue](https://user-images.githubusercontent.com/81999657/148938527-9db34fee-1d62-400a-8f61-83a10b748449.PNG)

**Comment by ifranckie** [comment] 2022-01-11 13:26
i have the same issue, hope this will be fixed

**Comment by keone** [comment] 2022-01-11 15:45
that's not the issue, the issue is the link needs to be from raw.githubusercontent.com, i.e. `https://raw.githubusercontent.com/Jacob130000x/booboologo/main/booboologo.png`

**Comment by keone** [comment] 2022-01-12 06:25
this re-adds the block for `29nBhWM2qRqSkttsX29pUwcNyDeznVbtN4HqkQjvYqxt` instead of modifying the existing.
see https://github.com/solana-labs/token-list/pull/13493/checks?check_run_id=4779597811

**Comment by Jacob130000x** [comment] 2022-01-12 13:31
Hi @keone sorry for being a pain in the bum. I have created a new request seems like I am getting a new error: unsupported file modified: /dev/null 

PR: https://github.com/solana-labs/token-list/pull/13653

**Comment by keone** [comment] 2022-01-12 15:22
great! no problem, merged

**Closed by keone** 2022-01-12 15:22 UTC
