### ISSUE TITLE
The application of token information to the revised content failed. What should I do?

### ISSUE THREAD

**Issue by quiztok** [solana-labs/token-list#17250] opened 2022-02-05 06:46 UTC
- **I'm submitting a ...**
  [ X  ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

Hello, I completed the token swap (ERC20 -> SPL-Token) with wormhole this time and changed the token name and symbol, but the details reflected after the change request were slightly different from what I expected, so I tried to modify it (update git token-list), but it is not reflected. The PR link for the error is as follows. What should I do if I want to modify it?

Token information to be updated.
 name : QUIZTOK
 symbol : QTCON-SOL

https://github.com/solana-labs/token-list/pull/17209

https://github.com/solana-labs/token-list/commit/46112dbf918639473bb303ede4ce912da1d8c277

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment] 2022-02-06 02:24
duplicate of #17212

**Closed by keone** 2022-02-06 02:24 UTC
