### ISSUE TITLE
unknown token shown in phantom wallet

### ISSUE THREAD

**Issue by fubukyx** [solana-labs/token-list#12343] opened 2022-01-04 13:43 UTC
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
  hello, i created my token 5 days ago and the project was merged 2 days ago. The problem is that the token i created is detected on solscan.io with name and logo, while on phantom wallet it is still shown as unknown token with no logo. i tried reinstalling phantom wallet extension again but still getting the same problem.
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment] 2022-01-05 05:22
duplicate of #12189

**Closed by keone** 2022-01-05 05:22 UTC
