### ISSUE TITLE
Logo and Token Symbol not shown on phantom wallet? please help to check is there any wrong with our PR. Thank you

### ISSUE THREAD

**Issue by DookuSociety** [solana-labs/token-list#11798] opened 2021-12-31 19:22 UTC
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by keone** [comment] 2022-01-02 19:24
please link a PR

**Comment by Benomat** [comment] 2022-01-03 20:30
> please link a PR

I am having the same issue here is my PR: #12017 
and here my issue i opened for that: #12189

**Comment by keone** [comment] 2022-01-05 05:23
duplicate of #12189

**Closed by keone** 2022-01-05 05:23 UTC
