### ISSUE TITLE
Error validating schema: chainId: conflicting values 103 and 0.

### ISSUE THREAD

**Issue by JayMissionPh** [solana-labs/token-list#14949] opened 2022-01-20 19:19 UTC
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ X ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
 I follow a Video on youtube how to do it right for uploading and naming the project. I don't get why I am getting an error when it comes to error validating schema: chainId: conflicting values 103 and 0. Please help. 

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
Here is the tutorial I followed: https://www.youtube.com/watch?v=kVxueRjcm6A&t=834s he was able to change name and Add logo for his project.

**Comment by keone** [comment] 2022-01-20 21:35
duplicate of #14437

**Closed by keone** 2022-01-20 21:35 UTC
